class PresentationError(Exception): ...


class InvalidAccessTokenError(PresentationError): ...


class ExpiredAccessTokenError(PresentationError): ...


class InvalidCursorError(PresentationError): ...
