class ApplicationError(Exception): ...


class UsecaseError(ApplicationError): ...


class GatewayError(ApplicationError): ...


class GatewayFailedError(GatewayError): ...


class InconsistentDataError(GatewayError): ...


class ActorNotFoundError(UsecaseError): ...


class ChatNotFoundError(UsecaseError): ...


class ChatMembershipForbiddenError(UsecaseError): ...


class InvalidChatCommandError(UsecaseError): ...


class ConnectionClosedError(ApplicationError): ...
